### PR TITLE
Fix gradle sync and compilation error on Android Studio 3.4

### PR DESCRIPTION
**Pull request by uOOOO**
**Description**:
Migrate to AGP 3.4.0 and Gradle 5.4.1
Some scripts were from [here](https://github.com/uber/AutoDispose/pull/330/files/d8393185bd8b0297afb114f35bd5ad615cfd5331).

**Related issue(s)**:
#313

### CODE REVIEW

**Comment by uOOOO** [comment]
After rebasing onto #328, build always failed on travis-ci not local build. I can't find a solution. So I closed this PR.

```
 Task :tooling:rib-intellij-plugin:compileJava FAILED
<=======------> 59% EXECUTING [19m 17s]FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':tooling:rib-intellij-plugin:compileJava'.
> Could not resolve all files for configuration ':tooling:rib-intellij-plugin:compileClasspath'.
   > Could not find CheckStyle-IDEA/lib/log4j-1.2.17-unzipped.com.jetbrains.plugins.jar (unzipped.com.jetbrains.plugins:CheckStyle-IDEA:5.26.0).
     Searched in the following locations:
         file:/home/travis/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2017.2/5155889067278eb216234aa0eeb8e1944644624c/ideaIC-2017.2/plugins/CheckStyle-IDEA/CheckStyle-IDEA/lib/log4j-1.2.17.jar
         file:/home/travis/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/unzipped.com.jetbrains.plugins/CheckStyle-IDEA-5.26.0/CheckStyle-IDEA/lib/log4j-1.2.17.jar
   > Could not find CheckStyle-IDEA/lib/checkstyle-idea-5.26.0-unzipped.com.jetbrains.plugins.jar (unzipped.com.jetbrains.plugins:CheckStyle-IDEA:5.26.0).
     Searched in the following locations:
         file:/home/travis/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2017.2/5155889067278eb216234aa0eeb8e1944644624c/ideaIC-2017.2/plugins/CheckStyle-IDEA/CheckStyle-IDEA/lib/checkstyle-idea-5.26.0.jar
         file:/home/travis/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/unzipped.com.jetbrains.plugins/CheckStyle-IDEA-5.26.0/CheckStyle-IDEA/lib/checkstyle-idea-5.26.0.jar
   > Could not find CheckStyle-IDEA/lib/commons-codec-1.11-unzipped.com.jetbrains.plugins.jar (unzipped.com.jetbrains.plugins:CheckStyle-IDEA:5.26.0).
     Searched in the following locations:
         file:/home/travis/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2017.2/5155889067278eb216234aa0eeb8e1944644624c/ideaIC-2017.2/plugins/CheckStyle-IDEA/CheckStyle-IDEA/lib/commons-codec-1.11.jar
         file:/home/travis/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/unzipped.com.jetbrains.plugins/CheckStyle-IDEA-5.26.0/CheckStyle-IDEA/lib/commons-codec-1.11.jar
   > Could not find CheckStyle-IDEA/lib/commons-io-2.6-unzipped.com.jetbrains.plugins.jar (unzipped.com.jetbrains.plugins:CheckStyle-IDEA:5.26.0).
     Searched in the following locations:
         file:/home/travis/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2017.2/5155889067278eb216234aa0eeb8e1944644624c/ideaIC-2017.2/plugins/CheckStyle-IDEA/CheckStyle-IDEA/lib/commons-io-2.6.jar
         file:/home/travis/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/unzipped.com.jetbrains.plugins/CheckStyle-IDEA-5.26.0/CheckStyle-IDEA/lib/commons-io-2.6.jar
   > Could not find CheckStyle-IDEA/lib/jcl-over-slf4j-1.7.25-unzipped.com.jetbrains.plugins.jar (unzipped.com.jetbrains.plugins:CheckStyle-IDEA:5.26.0).
     Searched in the following locations:
         file:/home/travis/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2017.2/5155889067278eb216234aa0eeb8e1944644624c/ideaIC-2017.2/plugins/CheckStyle-IDEA/CheckStyle-IDEA/lib/jcl-over-slf4j-1.7.25.jar
         file:/home/travis/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/unzipped.com.jetbrains.plugins/CheckStyle-IDEA-5.26.0/CheckStyle-IDEA/lib/jcl-over-slf4j-1.7.25.jar
   > Could not find CheckStyle-IDEA/lib/slf4j-log4j12-1.7.25-unzipped.com.jetbrains.plugins.jar (unzipped.com.jetbrains.plugins:CheckStyle-IDEA:5.26.0).
     Searched in the following locations:
         file:/home/travis/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2017.2/5155889067278eb216234aa0eeb8e1944644624c/ideaIC-2017.2/plugins/CheckStyle-IDEA/CheckStyle-IDEA/lib/slf4j-log4j12-1.7.25.jar
         file:/home/travis/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/unzipped.com.jetbrains.plugins/CheckStyle-IDEA-5.26.0/CheckStyle-IDEA/lib/slf4j-log4j12-1.7.25.jar
   > Could not find CheckStyle-IDEA/lib/slf4j-api-1.7.25-unzipped.com.jetbrains.plugins.jar (unzipped.com.jetbrains.plugins:CheckStyle-IDEA:5.26.0).
     Searched in the following locations:
         file:/home/travis/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2017.2/5155889067278eb216234aa0eeb8e1944644624c/ideaIC-2017.2/plugins/CheckStyle-IDEA/CheckStyle-IDEA/lib/slf4j-api-1.7.25.jar
         file:/home/travis/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/unzipped.com.jetbrains.plugins/CheckStyle-IDEA-5.26.0/CheckStyle-IDEA/lib/slf4j-api-1.7.25.jar
```
